spring:
  datasource:
    url: jdbc:h2:~/h2/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090;MODE=MySQL;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=FALSE;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: embedded
  jpa:
    generate-ddl: on
  flyway:
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
  gson:
    pretty-printing: true
  batch:
    job:
      name: demo
      enabled: on
    jdbc:
      initialize-schema: always
logging:
  level:
    root: info
    web: info
    sql: debug
    cn.jawar.learn.spring3.domain: debug