spring:
  datasource:
    url: jdbc:h2:~/h2/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090;MODE=MySQL;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: on
logging:
  level:
    root: info
    web: info
    sql: debug
    cn.jawar.learn.spring3.domain: debug
